name: install_apk_plugin
description: fork from https://github.com/hui-z/flutter_install_plugin 
version: 1.0.0
homepage: https://github.com/hui-z/flutter_install_plugin

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.zaihui.installplugin
    pluginClass: InstallPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
